// The VS Code compatibility surface implemented by Zénit's Node host.
// Editor edits use shared unsaved buffers; resource operations use backend services.
const fs=require('node:fs'),path=require('node:path'),url=require('node:url');
class Disposable { constructor(fn=()=>{}){this.dispose=fn;} static from(...items){return new Disposable(()=>items.forEach(x=>x.dispose()));} }
class EventEmitter { constructor(){this.listeners=new Set();this.event=(fn,ctx,list)=>{const cb=ctx?fn.bind(ctx):fn;this.listeners.add(cb);const d=new Disposable(()=>this.listeners.delete(cb));list?.push(d);return d;};} fire(value){for(const fn of this.listeners)try{const r=fn(value);r?.catch?.(e=>console.error(e.message));}catch(e){console.error(e.message);}} dispose(){this.listeners.clear();} }
class Position { constructor(line,character){Object.assign(this,{line,character});} translate(line=0,character=0){return new Position(this.line+line,this.character+character);} with(line=this.line,character=this.character){return new Position(line,character);} isBefore(p){return this.compareTo(p)<0;} isBeforeOrEqual(p){return this.compareTo(p)<=0;} isAfter(p){return this.compareTo(p)>0;} isEqual(p){return this.compareTo(p)===0;} compareTo(p){return this.line-p.line||this.character-p.character;} }
class Range { constructor(a,b,c,d){this.start=typeof a==='number'?new Position(a,b):a;this.end=typeof a==='number'?new Position(c,d):b;} get isEmpty(){return this.start.isEqual(this.end);} get isSingleLine(){return this.start.line===this.end.line;} contains(p){return p.start?this.contains(p.start)&&this.contains(p.end):this.start.isBeforeOrEqual(p)&&p.isBeforeOrEqual(this.end);} with(a=this.start,b=this.end){return new Range(a,b);} }
class Uri { constructor(value){this.value=value;const u=new URL(value);this.scheme=u.protocol.slice(0,-1);this.path=decodeURIComponent(u.pathname);this.query=u.search.slice(1);this.fragment=u.hash.slice(1);this.authority=u.host;this.fsPath=this.scheme==='file'?url.fileURLToPath(u):this.path;} toString(){return this.value;} toJSON(){return {$mid:1,scheme:this.scheme,path:this.path,external:this.value,fsPath:this.fsPath};} with(changes){const u=new URL(this.value);if(changes.path!==undefined)u.pathname=changes.path;if(changes.query!==undefined)u.search=changes.query;if(changes.fragment!==undefined)u.hash=changes.fragment;return new Uri(String(u));} static file(value){return new Uri(url.pathToFileURL(path.resolve(value)).href);} static parse(value){return new Uri(value);} static joinPath(base,...parts){return base.scheme==='file'?Uri.file(path.join(base.fsPath,...parts)):Uri.parse(new URL(parts.join('/'),base.toString()).href);} static from(v){return Uri.parse(`${v.scheme}://${v.authority||''}${v.path||''}${v.query?'?'+v.query:''}`);} }
class MarkdownString { constructor(value='',supportThemeIcons=false){Object.assign(this,{value,supportThemeIcons,isTrusted:false});} appendMarkdown(value){this.value+=value;return this;} appendText(value){this.value+=String(value).replace(/[\\`*_{}[\]()<>#+.!-]/g,'\\$&');return this;} appendCodeblock(value,language=''){return this.appendMarkdown('\n```'+language+'\n'+value+'\n```\n');} }
class RelativePattern {constructor(base,pattern){this.baseUri=typeof base==='string'?Uri.file(base):(base.uri||base);this.base=this.baseUri.fsPath;this.pattern=pattern;}}
class SnippetString {constructor(value=''){this.value=value;}appendText(v){this.value+=v;return this;}appendPlaceholder(v){this.value+='${1:'+v+'}';return this;}}
const enumeration=(names,start=0)=>Object.fromEntries(names.split(' ').map((n,i)=>[n,i+start]));
const itemClass=(keys)=>class{constructor(...args){keys.split(' ').forEach((key,i)=>this[key]=args[i]);}};
class TextEdit {constructor(range,newText){Object.assign(this,{range,newText});}static replace(r,t){return new TextEdit(r,t);}static insert(p,t){return new TextEdit(new Range(p,p),t);}static delete(r){return new TextEdit(r,'');}}
class CodeActionKind {
  constructor(value){this.value=value;}append(part){return new CodeActionKind(this.value?this.value+'.'+part:part);}
  contains(other){return !this.value||other.value===this.value||other.value.startsWith(this.value+'.');}
  intersects(other){return this.contains(other)||other.contains(this);}toJSON(){return this.value;}
}
for(const [name,value] of Object.entries({Empty:'',QuickFix:'quickfix',Refactor:'refactor',RefactorExtract:'refactor.extract',RefactorInline:'refactor.inline',RefactorRewrite:'refactor.rewrite',Source:'source',SourceOrganizeImports:'source.organizeImports',SourceFixAll:'source.fixAll'}))CodeActionKind[name]=new CodeActionKind(value);
class WorkspaceEdit {
  constructor(){this.changes=new Map();this.operations=[];}
  set(u,edits){const key=u.toString(),values=edits.map(e=>Array.isArray(e)?{...e[0],metadata:e[1]}:e);this.changes.set(key,values);this.operations=this.operations.filter(o=>o.kind!=='text'||o.uri.toString()!==key);this.operations.push({kind:'text',uri:u,edits:values});}
  get(u){return this.changes.get(u.toString())||[];}
  replace(u,r,t,metadata){const edit={...new TextEdit(r,t),metadata};this.changes.set(u.toString(),[...this.get(u),edit]);const last=this.operations.at(-1);if(last?.kind==='text'&&last.uri.toString()===u.toString())last.edits.push(edit);else this.operations.push({kind:'text',uri:u,edits:[edit]});}
  insert(u,p,t,metadata){this.replace(u,new Range(p,p),t,metadata);}delete(u,r,metadata){this.replace(u,r,'',metadata);}
  createFile(uri,options={},metadata){this.operations.push({kind:'create',uri,options:{...options,contents:undefined},contents:options.contents?[...options.contents]:undefined,metadata});}
  renameFile(oldUri,newUri,options={},metadata){this.operations.push({kind:'rename',oldUri,newUri,options,metadata});}
  deleteFile(uri,options={},metadata){this.operations.push({kind:'delete',uri,options,metadata});}
  has(u){return this.changes.has(u.toString());}entries(){return [...this.changes].map(([u,e])=>[Uri.parse(u),e]);}get size(){return this.changes.size;}
  toJSON(){return {changes:this.entries().map(([uri,edits])=>({uri,edits})),operations:this.operations};}
}
class SemanticTokensBuilder {constructor(legend){this.rows=[];this.legend=legend;}push(...v){if(v[0] instanceof Range){const [r,type,mods=[]]=v;if(!r.isSingleLine)throw Error('Un token semántico debe ocupar una sola línea.');const index=this.legend?.tokenTypes.indexOf(type);if(index===undefined||index<0)throw Error('Tipo de token no incluido en la leyenda: '+type);let bits=0;for(const mod of mods){const n=this.legend.tokenModifiers.indexOf(mod);if(n<0)throw Error('Modificador no incluido en la leyenda: '+mod);bits|=1<<n;}v=[r.start.line,r.start.character,r.end.character-r.start.character,index,bits];}this.rows.push(v);}build(){let line=0,col=0;const data=[];for(const [l,c,len,type,mods=0] of this.rows.sort((a,b)=>a[0]-b[0]||a[1]-b[1])){data.push(l-line,l===line?c-col:c,len,type,mods);line=l;col=c;}return {data:Uint32Array.from(data)};}}
module.exports=function createAPI(host,options){
  const {registerCommand,register,notify}=host,events=new Map(),diagnostics=new Map(),statusItems=new Set(),outputChannels=new Map(),virtual=new Map(),debugFactories=new Map(),taskProviders=new Map(),documents=new Map();let current=null;
  const event=name=>{if(!events.has(name))events.set(name,new EventEmitter());return events.get(name);};
  const storage=options.storage;fs.mkdirSync(storage,{recursive:true});
  const read=name=>{try{return JSON.parse(fs.readFileSync(path.join(storage,name),'utf8'));}catch{return {};}};
  const save=(name,value)=>{const target=path.join(storage,name),tmp=target+'.tmp';fs.writeFileSync(tmp,JSON.stringify(value));fs.renameSync(tmp,target);};
  const settings=read('configuration.json'),defaults={};
  const config=options.manifest.contributes?.configuration;
  for(const section of (Array.isArray(config)?config:[config]).filter(Boolean))for(const [key,value] of Object.entries(section.properties||{}))defaults[key]=value.default;
  const configuration=(section='')=>{
    const prefix=section?section+'.':'';const values={};for(const [key,val] of Object.entries({...defaults,...settings}))if(key.startsWith(prefix))values[key.slice(prefix.length)]=val;
    return Object.assign(values,{get:(key,fallback)=>settings[prefix+key]??defaults[prefix+key]??fallback,has:key=>prefix+key in settings||prefix+key in defaults,inspect:key=>({key:prefix+key,defaultValue:defaults[prefix+key],globalValue:settings[prefix+key]}),update:async(key,value)=>{const full=prefix+key;if(value===undefined)delete settings[full];else settings[full]=value;save('configuration.json',settings);event('configuration').fire({affectsConfiguration:s=>full===s||full.startsWith(s+'.')});}});
  };
  const makeDocument=data=>{
    const text=String(data.text||''),lines=text.split(/\r?\n/),u=data.uri||Uri.file(path.resolve(options.workspace,data.path));
    const offsetAt=p=>{let offset=0;const split=text.split('\n');for(let i=0;i<Math.min(p.line,split.length);i++)offset+=split[i].length+1;return Math.min(text.length,offset+p.character);};
    const positionAt=offset=>{const prefix=text.slice(0,offset),parts=prefix.split('\n');return new Position(parts.length-1,parts.at(-1).length);};
    const doc={uri:u,fileName:u.fsPath,languageId:data.language||'plaintext',version:data.version||1,isDirty:!!data.dirty,isClosed:false,isUntitled:false,eol:text.includes('\r\n')?2:1,lineCount:lines.length,offsetAt,positionAt,getText:r=>r?text.slice(offsetAt(r.start),offsetAt(r.end)):text,lineAt:n=>{n=typeof n==='number'?n:n.line;const t=lines[n]||'';return {lineNumber:n,text:t,range:new Range(n,0,n,t.length),rangeIncludingLineBreak:new Range(n,0,n<lines.length-1?n+1:n,n<lines.length-1?0:t.length),firstNonWhitespaceCharacterIndex:t.search(/\S/)<0?t.length:t.search(/\S/),isEmptyOrWhitespace:!t.trim()};},getWordRangeAtPosition:(p,re=/[A-Za-z_][\w]*/g)=>{const pattern=new RegExp(re.source,re.flags.includes('g')?re.flags:re.flags+'g');for(const m of lines[p.line].matchAll(pattern))if(m.index<=p.character&&m.index+m[0].length>=p.character)return new Range(p.line,m.index,p.line,m.index+m[0].length);},validatePosition:p=>new Position(Math.max(0,Math.min(p.line,lines.length-1)),Math.max(0,Math.min(p.character,lines[Math.max(0,Math.min(p.line,lines.length-1))].length))),validateRange:r=>new Range(doc.validatePosition(r.start),doc.validatePosition(r.end)),save:()=>saveDocument(u)};
    const previous=documents.get(u.toString());let raw;try{if(u.scheme==='file'&&!previous)raw=fs.readFileSync(u.fsPath);}catch(_){}
    doc._revision=data.revision??previous?._revision??(raw?require('node:crypto').createHash('sha256').update(raw).digest('hex'):null);doc._bom=previous?._bom??raw?.subarray(0,3).equals(Buffer.from([239,187,191]))??false;doc._newline=previous?._newline??(raw?.includes(Buffer.from('\r\n'))?'CRLF':'LF');return doc;
  };
  const syncDocument=data=>{
    if(!data?.path)return;const key=Uri.file(path.resolve(options.workspace,data.path)).toString(),previous=documents.get(key);const doc=makeDocument({...data,version:previous?previous.version+(previous.getText()!==data.text?1:0):1});documents.set(key,doc);const changed=current?.uri.toString()!==key;current=doc;
    if(!previous)event('open').fire(doc);else if(previous.getText()!==doc.getText())event('change').fire({document:doc,contentChanges:[{range:new Range(new Position(0,0),previous.positionAt(previous.getText().length)),rangeOffset:0,rangeLength:previous.getText().length,text:doc.getText()}]});
    if(changed)event('activeEditor').fire(vscode.window.activeTextEditor);
  };
  const selectorLanguages=selector=>[...new Set((Array.isArray(selector)?selector:[selector]).map(s=>typeof s==='string'?s:s.language||'*'))];
  const provider=(kind,method)=>(selector,p,...extra)=>Disposable.from(...selectorLanguages(selector).map(language=>register(kind,language,async c=>{
    const token={isCancellationRequested:false,onCancellationRequested:event('cancellation').event};
    const position=c.position?new Position(c.position.line,c.position.character):undefined;
    const range=c.range?new Range(new Position(c.range.start.line,c.range.start.character),new Position(c.range.end.line,c.range.end.character)):undefined;
    if(['semantic','symbols','codelens','folding','links','colors'].includes(kind))return kind==='folding'?p[method](current,{},token):p[method](current,token);
    const formatting=c.options||{tabSize:4,insertSpaces:true};
    if(kind==='format')return p[method](current,formatting,token);
    if(kind==='rangeFormat')return p[method](current,range,formatting,token);
    if(kind==='onTypeFormat')return p[method](current,position,c.character,formatting,token);
    if(kind==='colorPresentation')return p[method](c.color,{document:current,range},token);
    if(kind==='selection')return p[method](current,(c.positions||[]).map(p=>new Position(p.line,p.character)),token);
    if(kind==='highlights')return p[method](current,position,token);
    if(kind==='references')return p[method](current,position,{includeDeclaration:true},token);
    if(kind==='actions')return p[method](current,range,{diagnostics:(c.context?.diagnostics||[]).map(d=>({...d,range:new Range(new Position(d.range.start.line,d.range.start.character),new Position(d.range.end.line,d.range.end.character))})),triggerKind:c.context?.triggerKind||1,only:c.context?.only?new CodeActionKind(c.context.only):undefined},token);
    if(kind==='rename')return p[method](current,position,c.newName,token);
    if(kind==='signature')return p[method](current,position,token,{triggerKind:1,isRetrigger:false});
    return p[method](current,kind==='inlay'?range:position,token,{triggerKind:1,diagnostics:[]});
  },{legend:kind==='semantic'?extra[0]:undefined,triggers:extra.filter(x=>typeof x==='string'),resolver:kind==='actions'&&p.resolveCodeAction?(action)=>p.resolveCodeAction(action,{isCancellationRequested:false,onCancellationRequested:event('cancellation').event}):undefined})));
  const memento=name=>{const state=read(name);return {keys:()=>Object.keys(state),get:(key,fallback)=>state[key]??fallback,update:async(key,value)=>{if(value===undefined)delete state[key];else state[key]=value;save(name,state);},setKeysForSync:()=>{}};};
  const extensions=(options.extensions||[]).map(info=>({id:info.id,extensionPath:info.root,extensionUri:Uri.file(info.root),packageJSON:info.manifest,isActive:info.id===options.id,extensionKind:1,exports:undefined,activate:async()=>{if(info.id!==options.id)throw Error('Inicia la dependencia '+info.id+' desde Extensiones de Zénit.');return undefined;}}));
  const output=name=>{if(outputChannels.has(name))return outputChannels.get(name);let text='';const channel={name,append:t=>{text=(text+t).slice(-64000);console.info(t);},appendLine:t=>channel.append(t+'\n'),replace:t=>{text=String(t).slice(-64000);},clear:()=>{text='';},show:()=>host.effect({output:text,title:name}),hide:()=>{},dispose:()=>outputChannels.delete(name)};outputChannels.set(name,channel);return channel;};
  const vscode={version:'1.95.0',Disposable,EventEmitter,Position,Range,Uri,MarkdownString,SnippetString,TextEdit,WorkspaceEdit,SemanticTokensBuilder,
    SemanticTokensLegend:itemClass('tokenTypes tokenModifiers'),SemanticTokens:itemClass('data resultId'),Hover:itemClass('contents range'),CompletionItem:itemClass('label kind'),CompletionList:itemClass('items isIncomplete'),InlayHint:itemClass('position label kind'),CodeLens:itemClass('range command'),Location:class{constructor(uri,range){this.uri=uri;this.range=range instanceof Position?new Range(range,range):range;}},Diagnostic:itemClass('range message severity'),DiagnosticRelatedInformation:itemClass('location message'),DocumentSymbol:class{constructor(name,detail,kind,range,selectionRange){Object.assign(this,{name,detail,kind,range,selectionRange,children:[]});}},CodeAction:itemClass('title kind'),DebugAdapterExecutable:itemClass('command args options'),ThemeIcon:itemClass('id color'),ThemeColor:itemClass('id'),TreeItem:itemClass('label collapsibleState'),RelativePattern,Selection:class extends Range{constructor(...args){super(...args);this.anchor=this.start;this.active=this.end;}},CancellationTokenSource:class{constructor(){this.emitter=new EventEmitter();this.token={isCancellationRequested:false,onCancellationRequested:this.emitter.event};}cancel(){this.token.isCancellationRequested=true;this.emitter.fire();}dispose(){this.emitter.dispose();}},
    CompletionItemInsertTextRule:{KeepWhitespace:1,InsertAsSnippet:4},CompletionItemKind:enumeration('Text Method Function Constructor Field Variable Class Interface Module Property Unit Value Enum Keyword Snippet Color File Reference Folder EnumMember Constant Struct Event Operator TypeParameter'),SymbolKind:enumeration('File Module Namespace Package Class Method Property Field Constructor Enum Interface Function Variable Constant String Number Boolean Array Object Key Null EnumMember Struct Event Operator TypeParameter'),DiagnosticSeverity:enumeration('Error Warning Information Hint'),InlayHintKind:{Type:1,Parameter:2},StatusBarAlignment:{Left:1,Right:2},ConfigurationTarget:{Global:1,Workspace:2,WorkspaceFolder:3},ProgressLocation:{SourceControl:1,Window:10,Notification:15},ExtensionMode:{Production:1,Development:2,Test:3},UIKind:{Desktop:1,Web:2},EndOfLine:{LF:1,CRLF:2},TreeItemCollapsibleState:{None:0,Collapsed:1,Expanded:2},FileType:{Unknown:0,File:1,Directory:2,SymbolicLink:64},CodeActionKind,CodeActionTriggerKind:{Invoke:1,Automatic:2},DocumentHighlightKind:{Text:0,Read:1,Write:2},
    extensions:{all:extensions,getExtension:id=>extensions.find(e=>e.id.toLowerCase()===id.toLowerCase()),onDidChange:event('extensions').event},
    env:{appName:'Zénit',appHost:'desktop',language:options.locale||'es',uriScheme:'lumen',shell:options.shell,uiKind:1,isTelemetryEnabled:false,onDidChangeTelemetryEnabled:event('telemetry').event,machineId:'lumen-local',sessionId:process.pid.toString(),clipboard:{readText:async()=>{throw Error('Usa el portapapeles desde Zénit.');},writeText:async text=>host.effect({clipboard:text})},openExternal:async uri=>{host.effect({url:uri.toString()});return true;}},
    commands:{registerCommand,registerTextEditorCommand:(id,fn,ctx)=>registerCommand(id,async(...args)=>{const editor=vscode.window.activeTextEditor;if(!editor)return;const edit=new WorkspaceEdit(),builder={replace:(r,t)=>edit.replace(editor.document.uri,r,t),insert:(p,t)=>edit.insert(editor.document.uri,p,t),delete:r=>edit.delete(editor.document.uri,r)};await fn.call(ctx,editor,builder,...args);return vscode.workspace.applyEdit(edit);}),executeCommand:async(id,...args)=>host.execute(id,args),getCommands:async()=>host.commandIds()},
    workspace:{name:path.basename(options.workspace),rootPath:options.workspace,isTrusted:true,workspaceFolders:[{uri:Uri.file(options.workspace),name:path.basename(options.workspace),index:0}],get textDocuments(){return [...documents.values()];},getConfiguration:configuration,onDidChangeConfiguration:event('configuration').event,onDidOpenTextDocument:event('open').event,onDidChangeTextDocument:event('change').event,onDidSaveTextDocument:event('save').event,onDidCloseTextDocument:event('close').event,onDidChangeWorkspaceFolders:event('folders').event,onDidGrantWorkspaceTrust:event('trust').event,getWorkspaceFolder:u=>path.relative(options.workspace,u.fsPath).startsWith('..')?undefined:vscode.workspace.workspaceFolders[0],asRelativePath:u=>path.relative(options.workspace,typeof u==='string'?u:u.fsPath),registerTextDocumentContentProvider:(scheme,p)=>{virtual.set(scheme,p);return new Disposable(()=>virtual.delete(scheme));},openTextDocument:async value=>{const u=typeof value==='string'?Uri.file(value):value;if(documents.has(u.toString()))return documents.get(u.toString());const text=virtual.has(u.scheme)?await virtual.get(u.scheme).provideTextDocumentContent(u):fs.readFileSync(u.fsPath,'utf8');const doc=makeDocument({uri:u,text,path:u.fsPath});documents.set(u.toString(),doc);return doc;},applyEdit:async edit=>{for(const [u,edits] of edit.entries())host.effect({edits,path:u.fsPath});return false;},fs:{readFile:async u=>fs.promises.readFile(u.fsPath),stat:async u=>{const s=await fs.promises.stat(u.fsPath);return {type:s.isDirectory()?2:1,ctime:s.ctimeMs,mtime:s.mtimeMs,size:s.size};},readDirectory:async u=>(await fs.promises.readdir(u.fsPath,{withFileTypes:true})).map(e=>[e.name,e.isDirectory()?2:1])}},
    window:{get activeTextEditor(){return current?{document:current,selection:new vscode.Selection(0,0,0,0),selections:[new vscode.Selection(0,0,0,0)],options:{tabSize:4,insertSpaces:true},edit:async fn=>{const edits=[];fn({replace:(r,t)=>edits.push(TextEdit.replace(r,t)),insert:(p,t)=>edits.push(TextEdit.insert(p,t)),delete:r=>edits.push(TextEdit.delete(r))});const edit=new WorkspaceEdit();edit.set(current.uri,edits);return vscode.workspace.applyEdit(edit);}}:undefined;},get visibleTextEditors(){return current?[this.activeTextEditor]:[];},onDidChangeActiveTextEditor:event('activeEditor').event,onDidChangeVisibleTextEditors:event('visibleEditors').event,onDidChangeTextEditorSelection:event('selection').event,onDidChangeActiveColorTheme:event('theme').event,activeColorTheme:{kind:1},state:{focused:true},onDidChangeWindowState:event('windowState').event,showInformationMessage:async message=>{notify(message);return undefined;},showWarningMessage:async message=>{notify(message);return undefined;},showErrorMessage:async message=>{notify(message);return undefined;},createOutputChannel:output,createStatusBarItem:()=>{const item={text:'',tooltip:'',show:()=>statusItems.add(item),hide:()=>statusItems.delete(item),dispose:()=>statusItems.delete(item)};return item;},withProgress:async(opts,fn)=>fn({report:v=>{if(v.message)notify(v.message);}},{isCancellationRequested:false,onCancellationRequested:event('cancelProgress').event}),showTextDocument:async doc=>{host.effect({open:doc.uri?.fsPath||String(doc)});return vscode.window.activeTextEditor;},createTerminal:options=>{const terminal={name:typeof options==='string'?options:options.name,sendText:text=>host.effect({terminal:text,name:terminal.name}),show:()=>{},dispose:()=>{}};return terminal;}},
    languages:{createDiagnosticCollection:name=>{const map=new Map();diagnostics.set(name,map);return {name,set:(u,items)=>{if(Array.isArray(u)){for(const [uri,ds] of u)map.set(uri.toString(),ds);}else if(items===undefined)map.delete(u.toString());else map.set(u.toString(),items);},get:u=>map.get(u.toString()),delete:u=>map.delete(u.toString()),clear:()=>map.clear(),dispose:()=>diagnostics.delete(name)};},getDiagnostics:u=>u?[...diagnostics.values()].flatMap(m=>m.get(u.toString())||[]):[...diagnostics.values()].flatMap(m=>[...m]),registerCompletionItemProvider:provider('completion','provideCompletionItems'),registerDefinitionProvider:provider('definition','provideDefinition'),registerInlayHintsProvider:provider('inlay','provideInlayHints'),registerHoverProvider:provider('hover','provideHover'),registerReferenceProvider:provider('references','provideReferences'),registerDocumentSymbolProvider:provider('symbols','provideDocumentSymbols'),registerCodeLensProvider:provider('codelens','provideCodeLenses'),registerCodeActionsProvider:provider('actions','provideCodeActions'),registerDocumentFormattingEditProvider:provider('format','provideDocumentFormattingEdits'),registerOnTypeFormattingEditProvider:provider('onTypeFormat','provideOnTypeFormattingEdits'),registerDocumentRangeFormattingEditProvider:provider('rangeFormat','provideDocumentRangeFormattingEdits'),registerDocumentHighlightProvider:provider('highlights','provideDocumentHighlights'),registerSelectionRangeProvider:provider('selection','provideSelectionRanges'),registerColorProvider:(selector,p)=>Disposable.from(provider('colors','provideDocumentColors')(selector,p),provider('colorPresentation','provideColorPresentations')(selector,p)),registerRenameProvider:provider('rename','provideRenameEdits'),registerSignatureHelpProvider:provider('signature','provideSignatureHelp'),registerFoldingRangeProvider:provider('folding','provideFoldingRanges'),registerDocumentLinkProvider:provider('links','provideDocumentLinks'),registerDocumentSemanticTokensProvider:provider('semantic','provideDocumentSemanticTokens'),match:(s,d)=>selectorLanguages(s).includes(d.languageId)?10:0},
    debug:{registerDebugConfigurationProvider:(type,p)=>{debugFactories.set('config:'+type,p);return new Disposable(()=>debugFactories.delete('config:'+type));},registerDebugAdapterDescriptorFactory:(type,p)=>{debugFactories.set(type,p);return new Disposable(()=>debugFactories.delete(type));},startDebugging:async()=>{throw Error('La depuracion de plugins no esta conectada todavia. Usa los adaptadores de Zénit en Depuracion.');},onDidStartDebugSession:event('debugStart').event,onDidTerminateDebugSession:event('debugStop').event},
    tasks:{registerTaskProvider:(type,p)=>{taskProviders.set(type,p);return new Disposable(()=>taskProviders.delete(type));},onDidStartTask:event('taskStart').event,onDidEndTask:event('taskEnd').event,onDidEndTaskProcess:event('taskProcessEnd').event},
    l10n:{t:(text,...values)=>typeof text==='string'?text.replace(/\{(\d+)\}/g,(_,i)=>values[i]??''):text.message}
  };
  for(const [name,fields] of Object.entries({FileDecoration:'badge tooltip color',CallHierarchyItem:'kind name detail uri range selectionRange',TypeHierarchyItem:'kind name detail uri range selectionRange',DocumentHighlight:'range kind',DocumentLink:'range target',ParameterInformation:'label documentation',SignatureInformation:'label documentation',SignatureHelp:'signatures activeSignature activeParameter',SymbolInformation:'name kind containerName location',FoldingRange:'start end kind',SelectionRange:'range parent',InlineCompletionItem:'insertText range command',LinkedEditingRanges:'ranges wordPattern',Color:'red green blue alpha',ColorInformation:'range color',ColorPresentation:'label'}))vscode[name]=itemClass(fields);
  vscode.CancellationError=class extends Error{constructor(){super('Canceled');this.name='Canceled';}};
  // Zénit disables extension telemetry: expose its state without invoking a sender.
  vscode.env.createTelemetryLogger=()=>({isUsageEnabled:false,isErrorsEnabled:false,onDidChangeEnableStates:event('telemetry').event,logUsage(){},logError(){},dispose(){}});
  vscode.FileSystemError=class extends Error{static FileNotFound(v){return new this('File not found: '+v);}static FileExists(v){return new this('File exists: '+v);}static NoPermissions(v){return new this('No permissions: '+v);}static Unavailable(v){return new this('Unavailable: '+v);}};
  vscode.LogLevel={Off:0,Trace:1,Debug:2,Info:3,Warning:4,Error:5};
  vscode.workspace.onDidCreateFiles=event('createFiles').event;vscode.workspace.onDidDeleteFiles=event('deleteFiles').event;vscode.workspace.onDidRenameFiles=event('renameFiles').event;
  vscode.workspace.fs.writeFile=async(u,data)=>{const existed=fs.existsSync(u.fsPath);await fs.promises.writeFile(u.fsPath,data);if(!existed)event('createFiles').fire({files:[u]});};
  vscode.workspace.fs.createDirectory=async u=>fs.promises.mkdir(u.fsPath,{recursive:true});
  vscode.workspace.fs.delete=async(u,opts={})=>{await fs.promises.rm(u.fsPath,{recursive:!!opts.recursive});event('deleteFiles').fire({files:[u]});};
  vscode.workspace.fs.rename=async(a,b,opts={})=>{if(!opts.overwrite&&fs.existsSync(b.fsPath))throw vscode.FileSystemError.FileExists(b);await fs.promises.rename(a.fsPath,b.fsPath);event('renameFiles').fire({files:[{oldUri:a,newUri:b}]});};
  vscode.workspace.fs.copy=async(a,b,opts={})=>fs.promises.cp(a.fsPath,b.fsPath,{recursive:true,force:!!opts.overwrite,errorOnExist:!opts.overwrite});
  const globPattern=pattern=>{
    const raw=String(pattern);let re='^';for(let i=0;i<raw.length;i++){const c=raw[i];if(c==='*'){if(raw[i+1]==='*'){i++;if(raw[i+1]==='/'){i++;re+='(?:.*/)?';}else re+='.*';}else re+='[^/]*';}else if(c==='?')re+='[^/]';else if(c==='{')re+='(?:';else if(c==='}')re+=')';else if(c===',')re+='|';else re+=c.replace(/[.()+^$|[\]\\]/g,'\\$&');}return new RegExp(re+'$');
  };
  vscode.workspace.findFiles=async(include,exclude,maxResults=10000,token)=>{
    const base=typeof include==='string'?options.workspace:include.baseUri?.fsPath||include.base||options.workspace,match=globPattern(typeof include==='string'?include:include.pattern),skip=exclude?globPattern(typeof exclude==='string'?exclude:exclude.pattern):null,out=[];
    async function visit(folder){for(const e of await fs.promises.readdir(folder,{withFileTypes:true})){if(out.length>=maxResults||token?.isCancellationRequested)return;if(e.isSymbolicLink())continue;const file=path.join(folder,e.name),relative=path.relative(base,file).split(path.sep).join('/');if(skip?.test(relative))continue;if(e.isDirectory()){if(!['.git','node_modules','.runtime-data'].includes(e.name))await visit(file);}else if(match.test(relative))out.push(Uri.file(file));}}
    await visit(base);return out;
  };
  vscode.workspace.createFileSystemWatcher=(pattern,ignoreCreate=false,ignoreChange=false,ignoreDelete=false)=>{
    const base=typeof pattern==='string'?options.workspace:pattern.baseUri?.fsPath||pattern.base||options.workspace,match=globPattern(typeof pattern==='string'?pattern:pattern.pattern),create=new EventEmitter(),change=new EventEmitter(),remove=new EventEmitter(),known=new Set();
    const watcher=fs.watch(base,{recursive:true},(kind,name)=>{if(!name)return;const relative=String(name).split(path.sep).join('/');if(!match.test(relative))return;const file=path.join(base,String(name)),uri=Uri.file(file),exists=fs.existsSync(file);if(kind==='change'){if(!ignoreChange)change.fire(uri);}else if(exists){if(known.has(file)){if(!ignoreChange)change.fire(uri);}else{known.add(file);if(!ignoreCreate)create.fire(uri);}}else{known.delete(file);if(!ignoreDelete)remove.fire(uri);}});
    return {ignoreCreateEvents:ignoreCreate,ignoreChangeEvents:ignoreChange,ignoreDeleteEvents:ignoreDelete,onDidCreate:create.event,onDidChange:change.event,onDidDelete:remove.event,dispose(){watcher.close();create.dispose();change.dispose();remove.dispose();}};
  };
  vscode.commands.registerCommand=(id,fn,ctx)=>{const bound=(...args)=>fn.apply(ctx,args);bound.vscodeCommand=true;return registerCommand(id,bound,id);};
  const treeViews=require('./extension_views.cjs')(vscode);
  const services=require('./extension_services.cjs')(vscode,host,options,event,makeDocument,documents);
  vscode.workspace.applyEdit=async edit=>{
    if(!host.service)throw Error('Servicios del IDE no conectados.');
    const result=await host.service('workspace.applyEdit',{edit,documents:[...documents.values()].map(d=>({uri:d.uri,text:d.getText(),version:d.version}))});
    for(const resource of result.resources||[]){
      const uri=Uri.file(path.resolve(options.workspace,resource.path));
      if(resource.kind==='rename'){const oldUri=Uri.file(path.resolve(options.workspace,resource.oldPath));for(const [key,old] of [...documents])if(old.fileName===oldUri.fsPath||old.fileName.startsWith(oldUri.fsPath+path.sep)){documents.delete(key);const target=Uri.file(uri.fsPath+old.fileName.slice(oldUri.fsPath.length)),doc=makeDocument({uri:target,text:old.getText(),language:old.languageId,dirty:old.isDirty,version:old.version+1});documents.set(target.toString(),doc);if(current===old)current=doc;}event('renameFiles').fire({files:[{oldUri,newUri:uri}]});}
      if(resource.kind==='create')event('createFiles').fire({files:[uri]});
      if(resource.kind==='delete'){for(const [key,old] of [...documents])if(old.fileName===uri.fsPath||old.fileName.startsWith(uri.fsPath+path.sep)){old.isClosed=true;documents.delete(key);if(current===old)current=null;event('close').fire(old);}event('deleteFiles').fire({files:[uri]});}
    }
    for(const item of result.buffers||[]){const uri=Uri.file(path.resolve(options.workspace,item.path)),old=documents.get(uri.toString()),doc=makeDocument({uri,text:item.text,language:old?.languageId,dirty:true,version:(old?.version||0)+1});documents.set(uri.toString(),doc);if(current===old)current=doc;event('change').fire({document:doc,contentChanges:[{rangeOffset:0,rangeLength:item.before.length,text:item.text}]});}
    return result.applied===true;
  };
  const unsupportedApis=new Set();
  const decorationProviders=new Set();let decorationRevision=0,decorationPaths='';
  vscode.window.registerFileDecorationProvider=provider=>{
    if(typeof provider.provideFileDecoration!=='function')throw Error('FileDecorationProvider requiere provideFileDecoration.');
    decorationProviders.add(provider);decorationRevision++;
    const changed=provider.onDidChangeFileDecorations?.(()=>decorationRevision++);
    return new Disposable(()=>{changed?.dispose();decorationProviders.delete(provider);decorationRevision++;});
  };
  async function fileDecorations(paths,revision){
    const key=JSON.stringify(paths);if(revision===decorationRevision&&key===decorationPaths)return {revision,unchanged:true};
    decorationPaths=key;const startRevision=decorationRevision,items=[],values=new Map();
    // Evaluate descendants of visible folders so propagation also works when folded.
    const candidates=new Set(paths);
    for(const folder of paths){const absolute=path.resolve(options.workspace,folder);if(!fs.existsSync(absolute)||!fs.statSync(absolute).isDirectory())continue;const pending=[absolute];while(pending.length&&candidates.size<10000){const root=pending.pop();for(const entry of fs.readdirSync(root,{withFileTypes:true})){if(entry.isSymbolicLink()||['.git','node_modules','.runtime-data'].includes(entry.name))continue;const target=path.join(root,entry.name);if(entry.isDirectory())pending.push(target);else candidates.add(path.relative(options.workspace,target).split(path.sep).join('/'));if(candidates.size>=10000)break;}}}
    for(const file of candidates){
      const uri=Uri.file(path.resolve(options.workspace,file));let decoration;
      for(const provider of decorationProviders){
        const value=await provider.provideFileDecoration(uri,{isCancellationRequested:false,onCancellationRequested:event('cancellation').event});
        if(value)decoration={...decoration,...value};
      }
      if(decoration)values.set(file,{badge:decoration.badge,tooltip:decoration.tooltip,color:decoration.color?.id,propagate:decoration.propagate});
    }
    for(const file of paths){let decoration=values.get(file);if(!decoration){const descendant=[...values].find(([child,d])=>d.propagate&&child.startsWith(file.replace(/\/$/,'')+'/'));decoration=descendant?.[1];}if(decoration)items.push({path:file,decoration});}
    return {revision:startRevision,items};
  }
  // Missing namespaces/methods fail by name, without pretending to implement them.
  for(const name of ['workspace','window','languages','extensions','debug','tasks','env'])vscode[name]=new Proxy(vscode[name],{get(target,key){if(key in target||typeof key==='symbol'||key==='then')return target[key];const api=`vscode.${name}.${key}`;if(!unsupportedApis.has(api))console.error('API pendiente: '+api);unsupportedApis.add(api);throw Error(`La extensión necesita ${api}, aún no disponible en Zénit preview.`);}});
  const context={subscriptions:[],extensionPath:options.root,extensionUri:Uri.file(options.root),extension:extensions.find(e=>e.id===options.id),extensionMode:1,storagePath:storage,globalStoragePath:storage,storageUri:Uri.file(storage),globalStorageUri:Uri.file(storage),logUri:Uri.file(storage),logPath:storage,asAbsolutePath:p=>path.join(options.root,p),workspaceState:memento('workspace-state.json'),globalState:memento('global-state.json'),environmentVariableCollection:{persistent:false,replace:()=>{throw Error('Configura variables del proceso desde Zénit.');}}};
  const failures=new WeakMap();
  vscode.workspace.onWillSaveTextDocument=event('willSave').event;
  vscode.TextDocumentSaveReason={Manual:1,AfterDelay:2,FocusOut:3};
  async function willSave(reason=1,doc=current){
    const edits=[],deadline=Date.now()+1500;
    for(const listener of event('willSave').listeners){
      if(Date.now()>=deadline)break;if((failures.get(listener)||0)>=3)continue;
      const pending=[];let dispatch=true,timer;
      try{
        const returned=listener({document:doc,reason,waitUntil:value=>{if(!dispatch)throw Error('waitUntil debe llamarse durante el evento de guardado.');pending.push(Promise.resolve(value));}});
        // A returned promise is not waitUntil, but its rejection must be consumed.
        returned?.catch?.(error=>console.error(error.message));dispatch=false;
        const values=await Promise.race([Promise.all(pending),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Tiempo de guardado agotado.')),Math.max(1,deadline-Date.now()));})]);
        for(const value of values)if(Array.isArray(value))edits.push(...value);
      }catch(error){failures.set(listener,(failures.get(listener)||0)+1);console.error(error.message);}
      finally{dispatch=false;clearTimeout(timer);}
    }
    return {edits};
  }
  async function saveDocument(uri){
    let doc=documents.get(uri.toString());if(!doc||doc.isClosed||uri.scheme!=='file'||!host.service)return false;
    const pending=await willSave(1,doc);
    if(doc!==documents.get(uri.toString()))return false;
    if(pending.edits.length){const edit=new vscode.WorkspaceEdit();edit.set(uri,pending.edits);try{if(!await vscode.workspace.applyEdit(edit))return false;}catch(_){return false;}doc=documents.get(uri.toString());}
    const result=await host.service('workspace.saveDocument',{uri,text:doc.getText(),revision:doc._revision,newline:doc._newline,bom:doc._bom});
    if(!result.saved)return false;doc._revision=result.buffer.revision;doc.isDirty=false;event('save').fire(doc);return true;
  }
  vscode.workspace.saveAll=async(includeUntitled=false)=>{let success=true;for(const doc of [...documents.values()])if(doc.isDirty){if(doc.isUntitled){if(includeUntitled)success=false;continue;}if(!await saveDocument(doc.uri))success=false;}return success;};
  const updateEditors=require('./extension_editors.cjs')(vscode,options,event,makeDocument,documents,doc=>{current=doc;});
  const serviceEvent=services.event;services.event=(name,value)=>{if(name==='editor.state'){updateEditors(value);return;}if(name==='document.saved'){const uri=Uri.file(value.uri),old=documents.get(uri.toString());if(old&&old.getText()===value.text){old._revision=value.revision;old.isDirty=false;event('save').fire(old);}return;}return serviceEvent(name,value);};
  function didSave(){if(current){if(current.uri.scheme==='file')try{current._revision=require('node:crypto').createHash('sha256').update(fs.readFileSync(current.uri.fsPath)).digest('hex');}catch{}current.isDirty=false;event('save').fire(current);}}
  return {vscode,context,services,syncDocument,willSave,didSave,treeViews,fileDecorations,hasFileDecorations:()=>decorationProviders.size>0,unsupportedApis,getDiagnostics:()=>current?[...diagnostics.values()].flatMap(map=>map.get(current.uri.toString())||[]):[],diagnosticCollections:diagnostics,readVirtual:async value=>{const u=Uri.parse(value);const p=virtual.get(u.scheme);if(!p)throw Error('Documento virtual no registrado.');return p.provideTextDocumentContent(u);}};
};
