import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultLayout,normalizeLayout,setCollapsed,movePanel,LAYOUT_KEY} from '../web/src/layout-state.js';
import {ICON_NAMES,icon,fileIcon} from '../web/src/icons.js';

test('v3 state starts expanded with labelled navigation',()=>{const s=defaultLayout();assert.equal(s.version,3);assert.deepEqual(s.collapsed,[]);assert.equal(s.railCompact,false);assert.equal(LAYOUT_KEY,'lumen.layout.v3');});
test('v2 migration retains positions, active tabs, widths and visibility',()=>{const s=normalizeLayout({version:2,preset:'custom',groups:{left:['project','console'],right:['assistant'],bottom:[]},active:{left:'console'},sizes:{left:388,right:405},hidden:['assistant']});assert.equal(s.version,3);assert.equal(s.active.left,'console');assert.deepEqual(s.groups.left,['project','console']);assert.equal(s.sizes.right,405);assert.deepEqual(s.hidden,['assistant']);assert.deepEqual(s.collapsed,[]);});
test('collapse metadata rejects invalid sides and de-duplicates',()=>{const s=normalizeLayout({...defaultLayout(),collapsed:['left','left','bottom','right','<svg>'],railCompact:'yes'});assert.deepEqual(s.collapsed,['left','right']);assert.equal(s.railCompact,false);});
test('collapse leaves panel inventory, active content and widths untouched',()=>{const a=defaultLayout();a.sizes.left=396;const b=setCollapsed(a,'left');assert.deepEqual(b.groups,a.groups);assert.deepEqual(b.active,a.active);assert.deepEqual(b.sizes,a.sizes);assert.deepEqual(b.hidden,a.hidden);assert.deepEqual(a.collapsed,[]);assert.deepEqual(b.collapsed,['left']);});
test('invalid bottom or unknown collapse is a no-op',()=>{const a=defaultLayout();for(const x of ['bottom','evil',null])assert.deepEqual(setCollapsed(a,x),a);});
test('expand restores without resetting requested widths',()=>{const a=defaultLayout();a.sizes.right=470;const b=setCollapsed(setCollapsed(a,'right'),'right',false);assert.equal(b.sizes.right,470);assert.deepEqual(b.collapsed,[]);});
test('moving into a collapsed dock reveals that destination only',()=>{let a=setCollapsed(setCollapsed(defaultLayout(),'left'),'right');const b=movePanel(a,'console','right');assert.deepEqual(b.collapsed,['left']);assert.equal(b.active.right,'console');});
test('serialized compact and collapsed state round-trips unchanged',()=>{const a=setCollapsed(defaultLayout(),'right');a.railCompact=true;assert.deepEqual(normalizeLayout(JSON.parse(JSON.stringify(a))),a);});
test('1000 alternating transitions do not mutate inputs or multiply sides',()=>{let state=defaultLayout();for(let i=0;i<1000;i++){const before=JSON.stringify(state);const next=setCollapsed(state,i%2?'left':'right',i%3!==0);assert.equal(JSON.stringify(state),before);assert.equal(new Set(next.collapsed).size,next.collapsed.length);state=next;}});
test('original SVG family uses one 24-unit coordinate system with names',()=>{assert.ok(ICON_NAMES.length>=58);assert.equal(new Set(ICON_NAMES).size,ICON_NAMES.length);for(const name of ICON_NAMES){const output=icon(name);assert.match(output,/viewBox="0 0 24 24"/);assert.match(output,/aria-hidden="true"/);assert.match(output,/focusable="false"/);assert.ok(!output.includes('<script'));}});
test('C C++ ASM and all nC extension badges are local text / vectors',()=>{for(const ext of ['c','cpp','s','asm','n','nm','ncp','nb','nbb']){const output=fileIcon('example.'+ext);assert.ok(output.includes('file-type'));assert.ok(!/https?:/.test(output));}});
