/** One accessible glass listbox for every single-choice field, including dialogs. */
import {icon} from './icons.js';
const fields=new Map();let active=null,serial=0,queued=false;
const popup=document.createElement('div');popup.className='glass-options';popup.hidden=true;popup.setAttribute('role','listbox');popup.id='lumen-options';document.body.append(popup);
function close(focus=false){if(!active)return;const a=active;active=null;popup.hidden=true;popup.replaceChildren();a.button.setAttribute('aria-expanded','false');a.button.removeAttribute('aria-activedescendant');if(focus&&a.button.isConnected)a.button.focus();}
function place(){if(!active)return;const r=active.button.getBoundingClientRect();if(!r.width||!r.height){close();return;}const width=Math.min(Math.max(r.width,220),innerWidth-24);popup.style.width=width+'px';popup.style.left=Math.max(12,Math.min(r.left,innerWidth-width-12))+'px';const below=innerHeight-r.bottom-16,above=r.top-16;popup.style.maxHeight=Math.max(90,Math.min(300,Math.max(below,above)))+'px';popup.style.top=(below>=Math.min(popup.scrollHeight,300)||below>=above?r.bottom+7:Math.max(12,r.top-popup.offsetHeight-7))+'px';}
function highlight(index){if(!active)return;const items=[...popup.children];if(!items.length)return;active.index=Math.max(0,Math.min(index,items.length-1));items.forEach((item,i)=>item.classList.toggle('highlighted',i===active.index));active.button.setAttribute('aria-activedescendant',items[active.index].id);items[active.index].scrollIntoView({block:'nearest'});}
function choose(index){if(!active)return;const a=active,option=a.options[index];if(!option||option.disabled)return;a.select.value=option.value;close(true);sync(a);a.select.dispatchEvent(new Event('input',{bubbles:true}));a.select.dispatchEvent(new Event('change',{bubbles:true}));}
function open(a){close();if(a.select.disabled)return;sync(a);active=a;a.options=[...a.select.options].filter(o=>!o.hidden);popup.replaceChildren();a.options.forEach((option,i)=>{const b=document.createElement('div');b.className='glass-option';b.setAttribute('role','option');b.id='lumen-option-'+i;b.setAttribute('aria-selected',String(option.selected));b.setAttribute('aria-disabled',String(option.disabled));const label=document.createElement('span');label.textContent=option.label;b.append(label);if(option.selected)b.insertAdjacentHTML('beforeend',icon('check'));b.onpointerdown=e=>e.preventDefault();b.onclick=()=>choose(i);popup.append(b);});popup.hidden=false;a.button.setAttribute('aria-expanded','true');place();highlight(Math.max(0,a.options.findIndex(o=>o.selected)));}
function sync(a){const label=a.select.selectedOptions[0]?.label||'—';if(a.label.textContent!==label)a.label.textContent=label;a.button.disabled=a.select.disabled;const name=a.select.getAttribute('aria-label')||[...a.select.labels].map(l=>l.textContent.trim()).join(' ')||label;a.button.setAttribute('aria-label',name);}
function enhance(select){if(select.multiple||select.size>1||fields.has(select)||select.closest('.monaco-editor'))return;const style=getComputedStyle(select);if(style.display==='none')return;const wrap=document.createElement('span');wrap.className='glass-select';wrap.style.setProperty('--select-width',style.width);select.before(wrap);wrap.append(select);select.classList.add('glass-native-select');select.tabIndex=-1;select.setAttribute('aria-hidden','true');const button=document.createElement('button');button.type='button';button.className='glass-select-trigger';button.id=(select.id||'select-'+(++serial))+'-trigger';button.setAttribute('role','combobox');button.setAttribute('aria-haspopup','listbox');button.setAttribute('aria-controls',popup.id);button.setAttribute('aria-expanded','false');const label=document.createElement('span');button.append(label);button.insertAdjacentHTML('beforeend',icon('chevron-down'));wrap.append(button);const a={select,button,wrap,label,index:0,options:[]};fields.set(select,a);sync(a);select.addEventListener('change',()=>sync(a));button.onclick=()=>active===a?close():open(a);let search='',last=0;button.onkeydown=e=>{if(['ArrowDown','ArrowUp','Home','End','Enter',' ','Escape','Tab'].includes(e.key)){if(e.key==='Tab'){close();return;}if(e.key==='Escape'){if(active===a){e.preventDefault();e.stopPropagation();close(true);}return;}e.preventDefault();e.stopPropagation();if(active!==a){open(a);return;}if(e.key==='Enter'||e.key===' '){choose(a.index);return;}let index=e.key==='Home'?0:e.key==='End'?a.options.length-1:a.index+(e.key==='ArrowDown'?1:-1);while(a.options[index]?.disabled)index+=e.key==='ArrowUp'?-1:1;highlight(index);}else if(e.key.length===1&&!e.ctrlKey&&!e.altKey&&!e.metaKey){e.preventDefault();if(active!==a)open(a);const now=performance.now();search=now-last>700?e.key:search+e.key;last=now;const index=a.options.findIndex(o=>!o.disabled&&o.label.toLocaleLowerCase().startsWith(search.toLocaleLowerCase()));if(index>=0)highlight(index);}};}
function refresh(){queued=false;for(const [select,a] of fields){if(!select.isConnected){if(active===a)close();fields.delete(select);}else sync(a);}document.querySelectorAll('select').forEach(enhance);if(active&&!active.button.isConnected)close();}
const observer=new MutationObserver(records=>{if(records.every(r=>popup.contains(r.target)||r.target.closest?.('.glass-select-trigger')))return;if(!queued){queued=true;requestAnimationFrame(refresh);}});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled','selected']});refresh();
document.addEventListener('pointerdown',e=>{if(active&&!popup.contains(e.target)&&!active.wrap.contains(e.target))close();},true);
document.addEventListener('scroll',e=>{
  if(!active||popup.contains(e.target))return;
  // Scrolling a field into view can finish just after its listbox opens.
  // Keep the popover anchored instead of instantly closing it in that race.
  const r=active.button.getBoundingClientRect();
  if(r.bottom<12||r.top>innerHeight-12)close();else place();
},true);window.addEventListener('resize',()=>close());
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active){e.preventDefault();e.stopImmediatePropagation();close(true);}},true);
document.addEventListener('lumen:controls',refresh);
