import './controls.js';
import {icon,escapeHTML as esc} from './icons.js';
import {glassArt,createLumenScene} from './glass.js';
const root=document.querySelector('#installer');
let api=null,info={target:'%LOCALAPPDATA%\\Programs\\Zenit',bytes:0,available:false,winget:false},step=0,scenes=[],poll;
const options={locale:'es',packages:[],shortcuts:true,desktop:false};
const packages=[['python','Python','Python.Python.3.12'],['javascript','JavaScript / TypeScript','OpenJS.NodeJS.LTS'],['csharp','C# / F# · .NET SDK','Microsoft.DotNet.SDK.8'],['cpp','C / C++ · LLVM','LLVM.LLVM'],['java','Java · OpenJDK','Microsoft.OpenJDK.21'],['go','Go','GoLang.Go'],['rust','Rust','Rustlang.Rustup'],['git','Git','Git.Git'],['cmake','CMake','Kitware.CMake'],['asm','ASM · NASM','NASM.NASM'],['android','Android Studio · móvil','Google.AndroidStudio'],['android-tools','Android · Platform Tools / ADB','Google.PlatformTools']];
const text=(es,en)=>options.locale==='en'?en:es;
const names=()=>[text('Bienvenida','Welcome'),text('Idioma','Language'),text('Componentes','Components'),text('Configuración','Settings'),text('Instalación','Installing'),text('Finalizar','Finish')];
const localeSelect=()=>`<select id="setup-locale" aria-label="Idioma del instalador"><option value="es" ${options.locale==='es'?'selected':''}>Español</option><option value="en" ${options.locale==='en'?'selected':''}>English</option></select>`;
function render(){
  scenes.forEach(s=>s.dispose());scenes=[];
  root.innerHTML=`<header class="setup-brand"><img src="/assets/lumen.svg" alt="" width="25" height="30"><span class="brand-name">ZÉNIT <span>IDE</span></span><span class="brand-tagline">0.5.3 · R3</span><span>${text('Instalador','Installer')}</span></header><div class="setup-shell"><aside class="setup-sidebar"><nav>${names().map((n,i)=>`<div class="setup-step ${step===i?'active':''}"><span>${i<step?'✓':i+1}</span>${n}</div>`).join('')}</nav>${glassArt('orb')}<div class="install-motto"><strong>${text('Un lugar para<br>lo que viene.','A place for<br>what comes next.')}</strong><p>${text('Desarrolla. Imagina.<br>Con Zénit.','Develop. Imagine.<br>With Zénit.')}</p></div></aside><section class="setup-main"><header class="setup-heading"><h1>${[text('Bienvenido a Zénit','Welcome to Zénit'),text('Tu idioma, tu entorno.','Your language, your workspace.'),text('Elige tus herramientas.','Choose your tools.'),text('Todo, a tu medida.','Make it yours.'),text('Dando forma a tu espacio…','Creating your workspace…'),text('Un nuevo comienzo.','A new beginning.')][step]}</h1><p>${[text('El entorno de desarrollo moderno, potenciado por IA.','A modern development environment, powered by AI.'),text('Elige el idioma que se utilizará durante la instalación.','Choose the language used during installation.'),text('Instala solo lo que necesitas. Puedes añadir más herramientas después.','Install what you need. Add more tools later.'),text('Revisa la ubicación y los componentes antes de instalar.','Review the location and components before installing.'),text('Estamos preparando el editor y las herramientas que elegiste.','Preparing your editor and the tools you selected.'),text('Tu próxima idea ya tiene un lugar.','Your next idea has a home.')][step]}</p></header><div class="setup-content">${content()}</div><footer class="setup-footer"><button class="secondary-button" id="setup-cancel" ${step===4?'disabled':''}>${text('Cancelar','Cancel')}</button><div><button class="secondary-button" id="setup-back" ${step===0||step>=4?'disabled':''}>${text('Atrás','Back')}</button><button class="primary-button" id="setup-next" ${step===4||step===3&&!info.available?'disabled':''}>${step===3?text('Instalar Zénit','Install Zénit'):step===5?text('Abrir Zénit','Open Zénit'):text('Siguiente','Next')} ${icon('arrow-right')}</button></div></footer><p id="setup-error" role="alert"></p></section></div>`;
  root.querySelectorAll('canvas[data-glass]').forEach(async c=>{const s=await createLumenScene(c,true);if(!c.isConnected)s.dispose();else scenes.push(s);});
  if((step===2||step===3)&&api)loadSizes();
  document.querySelector('#setup-locale')?.addEventListener('change',e=>{options.locale=e.target.value;document.documentElement.lang=options.locale;render();});
  root.querySelectorAll('[data-package]').forEach(c=>c.onchange=()=>{options.packages=c.checked?[...options.packages,c.dataset.package]:options.packages.filter(p=>p!==c.dataset.package);});
  document.querySelector('#setup-shortcuts')?.addEventListener('change',e=>options.shortcuts=e.target.checked);
  document.querySelector('#setup-desktop')?.addEventListener('change',e=>options.desktop=e.target.checked);
  document.querySelector('#setup-browse')?.addEventListener('click',()=>safe(async()=>{if(api){info.target=await api.choose_directory();render();}}));
  document.querySelector('#skip-tools')?.addEventListener('click',()=>safe(async()=>{document.querySelector('#skip-tools').disabled=true;await api.skip_tools();}));
  document.querySelector('#setup-components')?.addEventListener('click',()=>{step=2;render();});
  document.querySelector('#setup-next').onclick=()=>safe(async()=>{if(step===3){if(!api)throw new Error('Abre el ejecutable del instalador para instalar Zénit.');await bridge('start',options);step=4;render();watch();}else if(step===5){await api.launch();}else{step++;render();}});
  document.querySelector('#setup-back').onclick=()=>{step--;render();};
  document.querySelector('#setup-cancel').onclick=()=>safe(()=>api?.close());
}
function content(){
  if(step===0)return `<section class="install-welcome"><div class="install-features">${[['sparkles','Desarrolla<br>más rápido','Herramientas inteligentes<br>para un flujo sin límites.'],['cube','Todo en un solo lugar','Código, pruebas, terminales<br>y desarrollo.'],['code','Hecho para<br>creadores','Flexible, abierto<br>y en constante evolución.']].map(([glyph,title,body])=>`<div><span>${icon(glyph)}</span><strong>${title}</strong><p>${body}</p></div>`).join('')}</div>${glassArt('orb','welcome-orb')}</section><article class="setup-card install-row"><span class="tile-icon">${icon('globe')}</span><div><h3>${text('Idioma del instalador','Installer language')}</h3><p>${text('Selecciona el idioma de la instalación.','Choose the installation language.')}</p></div>${localeSelect()}</article><article class="setup-card"><h3>${icon('cube')}${text('Componentes a instalar','Components to install')}</h3><p>${text('Un entorno completo, preparado para tus ideas.','A complete environment, ready for your ideas.')}</p><div class="install-component"><input type="checkbox" checked disabled><span><strong>Zénit 0.5.3</strong><small>Editor, Melody, depuración por lenguaje, terminales y extensiones</small></span><small>${info.bytes?(info.bytes/1048576).toFixed(0)+' MB':text('Incluido','Included')}</small></div><button class="install-component component-button" id="setup-components">${icon('code')}<span><strong>${text('Lenguajes y herramientas','Languages and tools')}</strong><small>Python, JavaScript / TypeScript, C#, C++, Java, Go, Rust</small></span>${icon('chevron-right')}</button></article><div class="install-footnote">${icon('shield')}${text('Instalación para tu usuario. Tus proyectos permanecen en su lugar.','Installed for your user. Your projects stay in place.')}</div>`;
  if(step===1)return `<div class="locale-composition"><div class="locale-illustration"><span>Hola.</span><span>Hello.</span><small>ZÉNIT / WORLD</small></div><article class="setup-card locale-card"><h3>${icon('globe')}${text('Idioma','Language')}</h3><p>${text('También será el idioma inicial de Zénit. Podrás cambiarlo en Ajustes.','This will also be the initial Zénit language. You can change it in Settings.')}</p>${localeSelect()}<div class="locale-preview"><small>${text('ASÍ TE DARÁ LA BIENVENIDA','YOUR WELCOME')}</small><strong>${text('Un lugar para lo que viene.','A place for what comes next.')}</strong><p>${text('Ideas más claras. Un futuro más tuyo.','Clearer ideas. A future of your own.')}</p></div></article></div>`;
  if(step===2)return `<article class="setup-card"><h3>${icon('check')}${text('Zénit · incluido','Zénit · included')}</h3><p>${text('Editor de código, terminales, Melody y Python integrado para ejecutar y depurar tus proyectos.','Code editor, terminals, Melody and built-in Python for running and debugging your projects.')}</p></article><article class="setup-card"><h3>${icon('code')}${text('SDK y herramientas adicionales','Additional SDKs and tools')}</h3><p>${text('Los componentes seleccionados se descargarán mediante winget. Sus licencias se aceptan al pulsar Instalar. Algunos paquetes no admiten instalación por usuario; se informará de cualquier resultado incompleto.','Selected components download through winget. Their licenses are accepted when you click Install. Some packages do not support user scope; any incomplete results will be reported.')}</p><div class="package-grid">${packages.map(([id,label,pkg])=>`<label class="package-option"><input type="checkbox" data-package="${id}" ${options.packages.includes(id)?'checked':''} ${info.winget?'':'disabled'}><span><strong>${label}</strong><small>${pkg}</small><small data-package-size="${id}">Consultando tamaño real de descarga…</small></span></label>`).join('')}</div>${!info.winget?`<p class="install-notice">${text('winget no está disponible. Zénit puede instalarse con todos sus componentes internos; los SDK se podrán preparar después.','winget is unavailable. Zénit can still install all internal components; SDKs can be prepared later.')}</p>`:''}</article>`;
  if(step===3)return `<article class="setup-card"><h3>${icon('folder')}${text('Ubicación de instalación','Install location')}</h3><div class="install-path"><code>${esc(info.target)}</code><button class="secondary-button" id="setup-browse" ${api?'':'disabled'}>${text('Cambiar','Change')}</button></div><div class="preference-row"><label for="setup-shortcuts">${text('Acceso en el menú Inicio','Start menu shortcut')}<small>${text('Encuentra Zénit junto a tus aplicaciones.','Find Zénit with your apps.')}</small></label><label class="platform-switch"><input type="checkbox" id="setup-shortcuts" ${options.shortcuts?'checked':''}><span></span></label></div><div class="preference-row"><label for="setup-desktop">${text('Acceso en el escritorio','Desktop shortcut')}<small>${text('Un acceso directo, siempre a mano.','A shortcut, always close by.')}</small></label><label class="platform-switch"><input type="checkbox" id="setup-desktop" ${options.desktop?'checked':''}><span></span></label></div></article><article class="setup-card"><h3>${icon('cube')}${text('Tu selección','Your selection')}</h3><p>Zénit 0.5.3 ${info.bytes?'· '+(info.bytes/1048576).toFixed(0)+' MB':''}</p><div class="install-selection">${options.packages.length?options.packages.map(id=>`<span>${icon('check')}${esc(packages.find(p=>p[0]===id)[1])}</span>`).join(''):`<span>${text('Todos los componentes internos. Sin SDK adicionales.','All internal components. No additional SDKs.')}</span>`}</div><div id="package-total" class="install-notice"></div><div id="package-breakdown"></div><p>${text('Al finalizar, el primer inicio te permitirá diseñar tu espacio de trabajo.','After installation, first launch lets you design your workspace.')}</p></article>${!info.available?`<div class="install-notice">${text('Vista previa. La instalación se realiza desde Zenit-0.5.3-R3-Windows-Setup.exe.','Preview. Install using Zenit-0.5.3-R3-Windows-Setup.exe.')}</div>`:''}`;
  if(step===4)return `<div class="install-progress">${glassArt('orb')}<h2 id="install-message">Preparando…</h2><progress id="install-progress" value="0" max="100"></progress><span id="install-percent">0%</span><p>${text('Puedes dejar esta ventana abierta mientras preparamos todo.','Keep this window open while everything is prepared.')}</p><div class="install-live-state"><i></i><span id="install-elapsed"></span></div><div id="install-packages" class="install-package-status"></div><button type="button" class="secondary-button" id="skip-tools" hidden>${text('Continuar sin las herramientas pendientes','Continue without pending tools')}</button><details class="install-details"><summary>${text('Detalles técnicos','Technical details')}</summary><pre id="install-log"></pre></details></div>`;
  return `<div class="setup-ready">${glassArt('orb')}<h2>${text('Bienvenido a Zénit.','Welcome to Zénit.')}</h2><p>${text('Todo listo para diseñar tu espacio<br>y empezar a crear.','Ready to design your workspace<br>and start creating.')}</p><span class="ready-badge">${icon('check')}Zénit 0.5.3</span><div id="install-warnings"></div></div>`;
}
async function bridge(method,...args){let timer;try{return await Promise.race([api[method](...args),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(text('La conexión tarda más de lo esperado. Reintentando…','Connection is taking longer than expected. Retrying…'))),10000);})]);}finally{clearTimeout(timer);}}
async function safe(fn){try{await fn();}catch(e){document.querySelector('#setup-error').textContent=e.message||String(e);}}
async function watch(){
  try{const s=await bridge('status');document.querySelector('#install-message').textContent=s.message;document.querySelector('#install-progress').value=s.progress;document.querySelector('#install-percent').textContent=s.progress+'%';document.querySelector('#install-log').textContent=s.log.join('\n');document.querySelector('#install-elapsed').textContent=text('En curso · ','In progress · ')+Math.floor((s.elapsed||0)/60)+'m '+(s.elapsed||0)%60+'s';document.querySelector('#skip-tools').hidden=s.phase!=='tools';const labels={pending:text('Pendiente','Pending'),checking:text('Comprobando','Checking'),installing:text('Instalando','Installing'),available:text('Disponible','Available'),warning:text('Revisar después','Review later'),skipped:text('Para después','For later')};document.querySelector('#install-packages').innerHTML=(s.packages||[]).map(p=>`<div data-state="${esc(p.status)}"><span>${icon(p.status==='available'?'check':p.status==='warning'?'info':'cube')}${esc(p.name)}</span><small>${labels[p.status]||esc(p.status)}</small></div>`).join('');
    if(s.status==='finished'){step=5;render();const pending=(s.packages||[]).filter(p=>['warning','skipped'].includes(p.status));document.querySelector('#install-warnings').innerHTML=(pending.length?`<p>${text('El editor está instalado. Herramientas para preparar después:','The editor is installed. Tools to prepare later:')} <strong>${pending.map(p=>esc(p.name)).join(', ')}</strong>.</p>`:'')+s.warnings.map(w=>`<p>${esc(w)}</p>`).join('');return;}
    if(s.status==='error'){document.querySelector('#setup-error').textContent=s.message;document.querySelector('#setup-cancel').disabled=false;document.querySelector('#setup-back').disabled=false;document.querySelector('#setup-back').onclick=()=>{step=3;render();};return;}
    poll=setTimeout(watch,700);
  }catch(e){document.querySelector('#setup-error').textContent=e.message;document.querySelector('#setup-cancel').disabled=false;poll=setTimeout(watch,1500);}
}
async function connected(){api=window.pywebview?.api;if(!api)return;try{info=await bridge('info');render();}catch(e){document.querySelector('#setup-error').textContent=e.message;}}
render();if(window.pywebview?.api)connected();else window.addEventListener('pywebviewready',connected,{once:true});
window.addEventListener('pagehide',()=>{clearTimeout(poll);scenes.forEach(s=>s.dispose());});

let sizeTimer;
const bytes=n=>n>=1e9?(n/1e9).toFixed(2)+' GB':(n/1e6).toFixed(2)+' MB';
async function loadSizes(){
  clearTimeout(sizeTimer);
  try{
    const plan=await api.package_sizes();
    for(const [id,item] of Object.entries(plan.items)){
      const el=document.querySelector(`[data-package-size="${id}"]`);if(!el)continue;
      el.textContent=(item.bytes==null?'Tamaño no publicado':bytes(item.bytes)+' de descarga')+(item.version?' · v'+item.version:'')+(item.dependencies?.length?' · '+item.dependencies.length+' dependencias':'')+(item.complete?' · Total verificado '+bytes(item.knownDownloadBytes):' · Total pendiente de verificar');
      el.title=(item.dependencies||[]).map(d=>d.package+': '+(d.bytes==null?'no publicado':bytes(d.bytes))).join('\n')+'\n'+(item.note||'');
    }
    const selected=options.packages.map(id=>plan.items[id]||{package:id,complete:false});
    const unique=new Map();let complete=true;
    const visit=item=>{if(!item.complete)complete=false;const key=item.package+'@'+(item.version||'');if(unique.has(key))return;unique.set(key,item);(item.dependencies||[]).forEach(visit);};selected.forEach(visit);
    const total=[...unique.values()].reduce((sum,item)=>sum+(item.bytes||0),0),summary=document.querySelector('#package-total');
    if(summary)summary.textContent=selected.length?(complete?'Descarga total verificada: ':'Descarga conocida: ')+bytes(total)+(complete?'':' · quedan componentes sin tamaño publicado.')+' El espacio instalado puede ser mayor.':'Sin descargas adicionales.';
    const detail=document.querySelector('#package-breakdown');if(detail)detail.innerHTML=[...unique.values()].map(item=>`<div class="preference-row"><span>${esc(item.package)}<small>${esc(item.note||'')}</small></span><strong>${item.bytes==null?'Sin publicar':bytes(item.bytes)}</strong></div>`).join('');
    if(plan.running&&(step===2||step===3))sizeTimer=setTimeout(loadSizes,1200);
  }catch(e){for(const el of document.querySelectorAll('[data-package-size]'))el.textContent='No se pudo consultar el tamaño: '+e.message;}
}
