const content=document.querySelector('#content');
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let api,info,selection={deleteData:false,deleteProjects:false},poll;
function step(n){for(let i=1;i<=3;i++)document.querySelector('#step'+i).toggleAttribute('aria-current',n===i);}
function choose(){step(1);content.innerHTML=`<p class="eyebrow">EDRYVO ${esc(info.version)}</p><h1>Un último ajuste.</h1><p>Desinstala Edryvo y decide qué queda en este equipo.</p><div class="choices"><label class="choice"><input type="checkbox" checked disabled><span><strong>Desinstalar Edryvo</strong><small>Retira la aplicación, sus versiones anteriores registradas y los accesos de Windows.</small></span></label><label class="choice"><input id="data" type="checkbox" ${selection.deleteData?'checked':''}><span><strong>Eliminar los datos guardados de Edryvo</strong><small>Perfil, foto, ajustes, conversaciones, extensiones, descargas y claves guardadas por Edryvo en este equipo.</small></span></label>${info.hasInternalProjects?`<label class="choice danger" id="project-choice" ${selection.deleteData?'':'hidden'}><input id="projects" type="checkbox" ${selection.deleteProjects?'checked':''}><span><strong>Eliminar también los proyectos internos</strong><small>Borra permanentemente el código y la memoria Lantern dentro de ${esc(info.internalProjects)}.</small></span></label>`:''}</div><div class="paths"><b>Aplicación</b><br>${esc(info.installation)}<br><b>Datos del usuario</b><br>${esc(info.dataDirectory)}</div><p class="note">Los proyectos en otras carpetas, sus archivos .lumen y los SDK instalados por separado se conservan. Las sesiones de Codex, Claude y Gemini pertenecen a sus aplicaciones.</p><footer class="actions"><button id="cancel">Conservar Edryvo</button><button id="review" class="primary">Revisar selección →</button></footer>`;
content.querySelector('#data').onchange=e=>{selection.deleteData=e.target.checked;if(!selection.deleteData)selection.deleteProjects=false;choose();};content.querySelector('#projects')?.addEventListener('change',e=>selection.deleteProjects=e.target.checked);content.querySelector('#cancel').onclick=()=>api.close();content.querySelector('#review').onclick=review;}
function review(){content.innerHTML=`<p class="eyebrow">REVISA TU SELECCIÓN</p><h1>Todo claro antes de salir.</h1><ul class="review-list"><li>Se eliminará la aplicación Edryvo.</li><li>${selection.deleteData?'Se eliminarán los datos locales y las claves guardadas por Edryvo.':'Se conservarán tus datos locales y tus claves.'}</li><li>${selection.deleteProjects?'Se eliminarán permanentemente tus proyectos internos.':'Se conservarán todos tus proyectos.'}</li></ul>${selection.deleteProjects?'<p class="error">El borrado de los proyectos internos no se puede deshacer.</p>':''}<p>Puedes volver atrás para cambiar la selección. Cierra las ventanas de Edryvo después de guardar tu trabajo.</p><footer class="actions"><button id="back">← Volver</button><button id="remove" class="remove">Desinstalar Edryvo</button></footer>`;content.querySelector('#back').onclick=choose;content.querySelector('#remove').onclick=async()=>{try{await api.start({...selection,confirm:true});watch();}catch(e){failure(String(e));}};}
function failure(message){clearTimeout(poll);content.innerHTML=`<h1>Queda un paso pendiente.</h1><p class="error">${esc(message)}</p><p>Los elementos que ya se han retirado no se vuelven a borrar. Puedes reintentar cuando hayas resuelto el problema.</p><footer class="actions"><button id="close">Cerrar</button><button class="primary" id="retry">Reintentar</button></footer>`;content.querySelector('#close').onclick=()=>api.close();content.querySelector('#retry').onclick=review;}
async function watch(){try{const state=await api.status();step(state.status==='finished'?3:2);if(state.status==='error'){failure(state.message);return;}if(state.status==='finished'){content.innerHTML=`<div class="result-icon">✓</div><h1>Hasta la próxima idea.</h1><p>Edryvo se ha desinstalado correctamente.</p><p>${selection.deleteData?'Se han retirado los datos seleccionados.':'Tu perfil y tus datos siguen disponibles para cuando vuelvas.'} ${selection.deleteProjects?'':'Tus proyectos se conservan.'}</p>${state.warnings.map(x=>`<p class="error">${esc(x)}</p>`).join('')}<footer class="actions"><button class="primary" id="close">Cerrar</button></footer>`;content.querySelector('#close').onclick=()=>api.close();return;}content.innerHTML=`<p class="eyebrow">DESINSTALANDO</p><h1>Cerrando esta etapa.</h1><p>${esc(state.message)}</p><progress max="100" value="${state.progress}" aria-label="Progreso de desinstalación"></progress><p class="note">${state.progress}% · Esta ventana sigue respondiendo mientras retiramos los archivos.</p>`;poll=setTimeout(watch,250);}catch(e){failure(String(e));}}
async function init(){api=window.pywebview.api;try{info=await api.info();choose();}catch(e){content.innerHTML=`<h1>No se puede abrir esta instalación.</h1><p class="error">${esc(String(e))}</p>`;}}
if(window.pywebview?.api)init();else window.addEventListener('pywebviewready',init,{once:true});
